language: node_js
node_js:
 - "node"
before_install:
  - npm install -g nyc
  - npm install -g codecov
  - npm install -g istanbul
script:
  - npm run ci-test
after_success:
  - npm run report-coverage