language: node_js
node_js:
 - "node"
install:
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec -t 38ab2362-4a14-40d8-8d42-93360ea44ccd
  - codecov